$:
  vscode:
    - docker:
      #  build: .ide/Dockerfile
      # 指定开发环境的代码服务端口
        # 指定开发环境镜像，可以是任意可访问的镜像。
        # 如果 image 指定的镜像中已安装 code-server 代码服务，将使用单容器模式启动开发环境
        # 如果 image 指定的镜像中未安装 code-server 代码服务，将使用双容器模式启动开发环境
        # 如下镜像为 CNB 默认开发环境镜像，已安装代码服务，将使用单容器模式启动开发环境
        # 可按需替换为其他镜像
        image: docker.cnb.cool/tryxd/default-build-env
        
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: ls
          script: ls -al

main:
  "crontab: 5 0 * * *":
    - runner:
        cpus: 64
      docker:
        image: ubuntu:latest
      stages:
        - name: Run script
          script: |
            chmod +x cfst
            ./cfst -httping -cfcolo HKG,KHH,NRT,LAX,SEA,SJC,FRA,MAD   -url "https://е.eu.org/300.zip" -sl 5
        - name: Commit changes
          script: |
            git config --local user.email "cnb@cnb.cool"
            git config --local user.name "CNB Action"
            git add .
            git commit -m "⌚️$(date +%Y%m%d%H%M%S)" -a
        - name: Push changes
          script: |
            git push